name: Bug Report
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report please check that your issue was not already discussed in the following:

        * [Issues](https://github.com/KatsuteDev/GitHub-Red-Issues/issues?q=is%3Aissue+is%3Aopen+label%3Abug%2C%22critical+bug%22)

        Please also check that:

        * This is actually a bug and not a feature.
        * You are running the latest version.

  - type: input
    attributes:
      label: Operating System
    validations:
      required: true

  - type: input
    attributes:
      label: Browser
    validations:
      required: true

  - type: input
    attributes:
      label: Extension Version
    validations:
      required: true

  - type: input
    attributes:
      label: Theme
      description: |
        Which GitHub theme you are using (ex: light/dark).
    validations:
      required: true

  - type: checkboxes
    id: component
    attributes:
      label: Components
      description: |
        Select which components are the wrong color.
      options:
        - label: Pinned issues
          required: false
        - label: Issues
          required: false
        - label: Issue timeline
          required: false
        - label: Issues tab
          required: false
        - label: Issue hovercard
          required: false
        - label: Pulls
          required: false
        - label: Pull timeline
          required: false
        - label: Pull hovercard
          required: false
        - label: Tasklist
          required: false
        - label: Discussions
          required: false
        - label: Subscriptions
          required: false
        - label: Search
          required: false
        - label: Print
          required: false
        - label: Project Boards
          required: false
        - label: Project Tables
          required: false
        - label: Insights
          required: false
        - label: Other (please specify)
          required: false

  - type: textarea
    attributes:
      label: Issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to replicate
      description: |
        Include steps to reproduce this issue.
    validations:
      required: true