name: Feature Request
description: Suggest a new feature
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Before opening a feature request please check that your idea was not already discussed in the following:

        * [Issues](https://github.com/KatsuteDev/GitHub-Red-Issues/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature+request%22)

        Please also check that:

        * This feature makes sense for the project.
        * This feature does not already exist.
        * You are running the latest version.

  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: |
        Explain your feature. Add any examples here.
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: |
        Explain why you think this feature should be added.
    validations:
      required: true